<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-UA1F7RES" failures="1" tests="2" name="com.automation.runners.RunnerForSalesForce" time="23.687" errors="0" timestamp="2023-11-11T17:54:12 PST" skipped="0">
  <testcase classname="com.automation.runners.RunnerForSalesForce" name="runScenario" time="8.539">
    <failure message="expected [Login | Salesforce] but found [Lightning Experience]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login | Salesforce] but found [Lightning Experience]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.automation.stepdefinitions.SalesForceStepDefinition.user_is_navigated_to_homepage(SalesForceStepDefinition.java:79)
at âœ½.user is navigated to homepage(file:///C:/Users/pradh/eclipse-workspace/CucumberSalesForceLogin/src/test/resources/features/SalesLogin.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="com.automation.runners.RunnerForSalesForce" name="runScenario" time="15.148"/>
  <system-out/>
</testsuite> <!-- com.automation.runners.RunnerForSalesForce -->
